name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
        description: "The tag to deploy"
jobs:
  push-container:
    name: Push Container
    uses: rosvik/workflows/.github/workflows/push-container.yml@main
    with:
      image: rosvik/tiny-ip
      registry_url: cubby.no
      registry_username: rosvik
      tag: ${{ github.event.inputs.tag || github.ref_name }}
    secrets:
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}
  cubbyman-reload:
    name: Cubbyman Reload
    needs: push-container
    uses: rosvik/workflows/.github/workflows/cubbyman-reload.yml@main
    with:
      base_url: https://cubby.no
    secrets:
      credentials: ${{ secrets.CUBBYMAN_CREDENTIALS }}
